name: CI

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Generate PDF from resume.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ github.action_path }}/resume.tex
      
      - name: Rename main.pdf to resume.pdf
        run: mv main.pdf resume.pdf
          
      - name: Release
        uses: softprops/action-gh-release@v1
